const API_BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:5000';
export const API_ENDPOINTS = {
  SIGNUP: `${API_BASE_URL}/api/auth/signup`,
  LOGIN: `${API_BASE_URL}/api/auth/login`,
  FORGOT_PASSWORD: `${API_BASE_URL}/api/auth/forgot-password`,
  VERIFY_OTP: `${API_BASE_URL}/api/auth/verify-otp`,
  RESET_PASSWORD: `${API_BASE_URL}/api/auth/reset-password`,
  PLUMBER_SIGNUP: `${API_BASE_URL}/api/plumber/signup`,
  PLUMBER_LOGIN: `${API_BASE_URL}/api/plumber/login`,
  PLUMBER_FORGOT_PASSWORD: `${API_BASE_URL}/api/plumber/forgot-password`,
  PLUMBER_VERIFY_OTP: `${API_BASE_URL}/api/plumber/verify-otp`,
  PLUMBER_RESET_PASSWORD: `${API_BASE_URL}/api/plumber/reset-password`,
  SELLER_SIGNUP: `${API_BASE_URL}/api/seller/signup`,
  SELLER_LOGIN: `${API_BASE_URL}/api/seller/login`,
  SELLER_FORGOT_PASSWORD: `${API_BASE_URL}/api/seller/forgot-password`,
  SELLER_VERIFY_OTP: `${API_BASE_URL}/api/seller/verify-otp`,
  SELLER_RESET_PASSWORD: `${API_BASE_URL}/api/seller/reset-password`,
  PLUMBER_PROFILE: `${API_BASE_URL}/api/plumber/profile`,
  ALL_PLUMBERS: `${API_BASE_URL}/api/plumber/all`,
  PLUMBER_SERVICES: `${API_BASE_URL}/api/plumber/services`,
  PLUMBER_SERVICE: `${API_BASE_URL}/api/plumber/service`,
  PLUMBER_BOOKINGS: `${API_BASE_URL}/api/plumber/bookings`,
  PLUMBER_BOOKING: `${API_BASE_URL}/api/plumber/booking`,
  SELLER_PROFILE: `${API_BASE_URL}/api/seller/profile`,
  PRODUCTS: `${API_BASE_URL}/api/products`,
  PRODUCTS_BY_CATEGORY: `${API_BASE_URL}/api/products/category`,
  PUBLIC_SERVICES: `${API_BASE_URL}/api/services/available`,
  HEALTH: `${API_BASE_URL}/api/health`
};
export default API_BASE_URL;
